-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  contact_name TEXT,
  email TEXT,
  plan TEXT,
  billing_cycle TEXT,
  recurring_amount REAL,
  activation_fee REAL,
  status TEXT,
  access_code TEXT,
  last_payment TEXT,
  next_billing_date TEXT,
  auto_renew BOOLEAN,
  gateway TEXT,
  card_token TEXT,
  retry_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  client_name TEXT,
  amount REAL,
  plan TEXT,
  billing_cycle TEXT,
  type TEXT,
  gateway TEXT,
  reference TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS webhook_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway TEXT,
  event_type TEXT,
  payload JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
